services:
  - type: web
    name: knowhub
    env: php
    buildCommand: composer install
    startCommand: vendor/bin/heroku-php-apache2
    envVars:
      - key: GOOGLE_CLIENT_ID
        value: "207510262129-19qlbi8qqudppurf1juulig88qd74qra.apps.googleusercontent.com"
      - key: GOOGLE_CLIENT_SECRET
        value: "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"
      - key: MEGA_EMAIL
        value: "your@email.com"
      - key: MEGA_PASSWORD
        value: "your-mega-password"
      - key: B2_KEY_ID
        value: "your-b2-key-id"
      - key: B2_APP_KEY
        value: "your-b2-app-key"
      - key: B2_BUCKET
        value: "your-b2-bucket"
      - key: FIREBASE_PROJECT_ID
        value: "your-project-id"
      - key: FIREBASE_API_KEY
        value: "your-api-key"
      - key: FIREBASE_BUCKET
        value: "your-bucket-name"
      - key: MEDIAFIRE_EMAIL
        value: "your@email.com"
      - key: MEDIAFIRE_PASSWORD
        value: "your-password"
      - key: MEDIAFIRE_TOKEN
        value: "your-dev-token"

databases:
  - name: archive-db
    databaseName: archive
    engine: postgres